server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # Оптимизация для favicon
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    # Конфигурация для проксирования видеопотока (исправление Mixed Content)
    # Все запросы к /stream/ проксируются на внутренний сервис video-capture
    location /stream/ {
        # Используйте имя сервиса из docker-compose
        proxy_pass https://v-1nqy.onrender.com; 

        # Настройки для потокового видео (MJPEG)
        proxy_buffering off;
        proxy_cache off;
        proxy_max_temp_file_size 0;

        # Необходимые заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Конфигурация для SPA (Single Page Application)
    # Если запрошенный URI не является существующим файлом или папкой, 
    # запрос передается файлу index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
    }
}